main: be.machigan.hidecitizen.HideCitizen
name: HideCitizen
version: ${project.version}
author: Machigan
api-version: 1.21
depend:
  - ProtocolLib
  - Citizens
  - LuckPerms

commands:
  hide-citizen:
    description: Hide citizen from players
    usage: /hide-citizen

permissions:
  hidecitizen.hide:
    default: op
    description: Allows player to hide citizen for other players
  hidecitizen.hidden.*:
    default: false
    description: Defines if a citizen is hidden or not
